import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('rotas, console, tema e acessibilidade',async({page})=>{
 test.setTimeout(60000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const route of ['inicio','trilhas','materias','aulas','exercicios','simulados','redacao','leituras','progresso','erros']){await page.goto('./#'+route);await expect(page.locator('h1')).toHaveCount(1);await expect(page.getByText('Carregando seu percurso…')).toHaveCount(0);const a=await new AxeBuilder({page}).analyze();expect(a.violations.map(x=>x.id+' '+x.description)).toEqual([]);}
 await page.getByRole('button',{name:'Ativar modo escuro'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','escuro');expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);expect(errors).toEqual([]);
});
test('salva respostas, retoma após recarregar e registra erros',async({page})=>{
 await page.goto('./#diagnostico/DIA-001-M1');await page.getByLabel('Sua resposta e os passos que utilizou').fill('85. Somei dezenas e unidades.');await page.getByRole('button',{name:'Próxima →'}).click();await expect(page.getByRole('heading',{name:'M2 · Registre seu raciocínio'})).toBeVisible();await page.getByLabel('Sua resposta e os passos que utilizou').fill('46');await page.waitForFunction(()=>new Promise(resolve=>{const r=indexedDB.open('reconstrucao-escolar');r.onsuccess=()=>{const q=r.result.transaction('study').objectStore('study').get('current');q.onsuccess=()=>{r.result.close();resolve(q.result?.answers?.['DIA-001-M2']==='46')}}}));await page.reload();await expect(page.getByLabel('Sua resposta e os passos que utilizou')).toHaveValue('46');await page.goto('./#inicio');await page.getByRole('link',{name:'Continuar estudando'}).click();await expect(page).toHaveURL(/DIA-001-M2/);await page.goto('./#erros');await page.getByLabel('Questão ou tópico').fill('DIA-001-M2');await page.getByLabel('Tipo de erro').selectOption('cálculo');await page.getByLabel('O que revisar e como tentar novamente').fill('Rever o reagrupamento.');await page.getByRole('button',{name:'Registrar erro'}).click();await expect(page.getByRole('heading',{name:'DIA-001-M2 · cálculo'})).toBeVisible();
});
test('celular, teclado e diagnóstico acessível',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('./#inicio');await expect(page.getByRole('link',{name:'Começar diagnóstico'})).toBeVisible();await expect(page.getByText('Carregando seu percurso…')).toHaveCount(0);await page.keyboard.press('Tab');await expect(page.getByText('Pular para o conteúdo')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('main')).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.goto('./#diagnostico/DIA-001-P1');await expect(page.getByLabel('Sua resposta e os passos que utilizou')).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations.map(v=>v.id)).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});

