const source={title:'ART-FUN-001 — Linguagens artísticas e leitura de obra — V2',url:'https://docs.google.com/document/d/15f2QMLEmsUWRk2VYjt9XqVRcVudxudnuh_pkFpiU8iM/edit',version:'V2'};
const base={"origin":"autoral","subject":"ART","topics":["ART-FUN-001"],"difficulty":"consolidação","layer":"CON","source":source,"reviewStatus":"revisado"};
export default [
{...base,"id":"ART-FUN-001-EX-CON-01","statement":"Uma fotografia tem o rosto muito iluminado e o restante do quadro em sombra. Explique como esse recurso pode organizar o olhar.","answer":"O contraste de valor entre rosto claro e fundo escuro pode criar ênfase e concentrar a atenção no rosto.","resolution":"A resposta deve relacionar uma evidência formal — diferença de claro e escuro — a um efeito compositivo — hierarquia visual ou ponto focal.","errorReasons":["Interpretação: afirmar um efeito sem indicar a evidência formal."]},
{...base,"id":"ART-FUN-001-EX-CON-02","statement":"Uma instalação usa placas de metal enferrujado em tamanho monumental. Por que não basta descrever apenas o tema representado?","answer":"Porque material, textura, escala e ocupação do espaço também participam da experiência e podem produzir sentidos.","resolution":"Em arte, a maneira material de construir integra a obra. Ignorar materialidade e escala reduz a análise ao assunto e perde relações formais importantes.","errorReasons":["Conteúdo: reduzir obra a tema ou narrativa."]},
{...base,"id":"ART-FUN-001-EX-CON-03","statement":"Explique por que uma obra abstrata não deve ser chamada automaticamente de “sem sentido”.","answer":"Porque abstração pode organizar cor, linha, gesto, matéria, ritmo e espaço de modo intencional, além de dialogar com contexto e referências.","resolution":"Ausência de figura reconhecível não significa ausência de organização ou possibilidade de interpretação. A leitura muda de foco: observa relações formais, materiais e contextuais.","errorReasons":["Generalização: equiparar não figurativo a aleatório."]},
{...base,"id":"ART-FUN-001-EX-CON-04","statement":"Um museu muda a ordem de exposição de três obras e acrescenta um novo texto de parede. Isso pode alterar a leitura do público? Explique.","answer":"Sim. A curadoria e a mediação criam relações, sequências e informações que orientam atenção e contexto, sem modificar fisicamente as obras.","resolution":"A experiência de recepção inclui o modo como a obra é apresentada. Mudanças de sequência e informação podem destacar comparações ou contextos diferentes.","errorReasons":["Conteúdo: imaginar que exposição é neutra."]},
{...base,"id":"ART-FUN-001-EX-CON-05","statement":"Uma imagem repete círculos iguais e interrompe o padrão com um triângulo. Identifique dois recursos compositivos.","answer":"Ritmo/repetição e contraste/ênfase no triângulo.","resolution":"Os círculos constroem expectativa por repetição; o triângulo rompe o padrão, produz contraste e tende a receber atenção.","errorReasons":["Memória: reconhecer apenas a figura diferente sem explicar o padrão."]},
{...base,"id":"ART-FUN-001-EX-CON-06","statement":"Por que conhecer uma entrevista do artista pode ajudar, mas não encerrar, a interpretação de uma obra?","answer":"Porque a intenção declarada é uma fonte contextual importante, mas a obra possui organização própria e pode receber interpretações em públicos e épocas diferentes.","resolution":"Intenção, obra e recepção são dimensões relacionadas, mas não idênticas. A entrevista não substitui a análise formal nem controla todos os efeitos posteriores.","errorReasons":["Estratégia: tratar intenção como tradução definitiva."]},
{...base,"id":"ART-FUN-001-EX-CON-07","statement":"Dê um exemplo de prática artística híbrida e explique quais linguagens combina.","answer":"Resposta possível: um videoclipe que combine música, atuação, dança e audiovisual.","resolution":"A resposta deve nomear uma prática concreta e explicar os recursos de mais de uma linguagem presentes nela. Apenas dizer “mistura tudo” não demonstra compreensão.","errorReasons":["Aplicação: citar hibridismo sem identificar linguagens."]},
{...base,"id":"ART-FUN-001-EX-CON-08","statement":"Transforme a frase “essa pintura é triste” em uma afirmação analítica baseada em evidência.","answer":"Exemplo: “A pintura pode produzir sensação de tristeza porque usa baixa luminosidade, figuras isoladas e grande área vazia ao redor delas”.","resolution":"A emoção deixa de ser rótulo e passa a ser hipótese sustentada por características observáveis. Outras evidências seriam possíveis, desde que coerentes.","errorReasons":["Argumentação: manter julgamento subjetivo sem evidência."]}
];
