const source={title:'ART-FUN-001 — Linguagens artísticas e leitura de obra — V2',url:'https://docs.google.com/document/d/15f2QMLEmsUWRk2VYjt9XqVRcVudxudnuh_pkFpiU8iM/edit',version:'V2'};
const base={"origin":"autoral","subject":"ART","topics":["ART-FUN-001"],"difficulty":"aprendizagem","layer":"APR","source":source,"reviewStatus":"revisado"};
export default [
{...base,"id":"ART-FUN-001-EX-APR-01","statement":"Explique por que dizer “arte é aquilo que é bonito” é uma definição insuficiente.","answer":"Porque noções de beleza variam historicamente e obras podem buscar estranhamento, crítica, memória, humor, denúncia ou experimentação, não apenas agradar.","resolution":"A definição reduz a diversidade de funções e efeitos da arte. Beleza pode participar de uma obra, mas não funciona como critério universal capaz de incluir todas as práticas artísticas.","errorReasons":["Conteúdo: reduzir arte à beleza ou ao gosto pessoal."]},
{...base,"id":"ART-FUN-001-EX-APR-02","statement":"Quais são as quatro linguagens artísticas de referência na organização escolar apresentada nesta aula?","answer":"Artes visuais, dança, música e teatro.","resolution":"Essas quatro linguagens funcionam como eixos de estudo na BNCC e ajudam a organizar práticas, embora existam obras híbridas que combinam recursos de mais de uma delas.","errorReasons":["Memória: omitir uma das quatro linguagens ou tratar as fronteiras como rígidas."]},
{...base,"id":"ART-FUN-001-EX-APR-03","statement":"Diferencie material, suporte e técnica usando um exemplo.","answer":"Exemplo: em uma aquarela, pigmento e água são materiais, o papel é suporte e a aplicação por aquarela é técnica.","resolution":"Material é aquilo manipulado, suporte é a base de realização e técnica é o procedimento. Em certas práticas as fronteiras podem variar, mas a distinção ajuda a observar a materialidade.","errorReasons":["Conteúdo: usar os três termos como sinônimos."]},
{...base,"id":"ART-FUN-001-EX-APR-04","statement":"Em uma imagem, uma única forma muito maior que todas as outras recebe atenção imediata. Qual relação compositiva está evidente?","answer":"Ênfase, produzida principalmente por contraste de escala.","resolution":"A diferença de tamanho cria contraste e faz a forma ganhar destaque relativo. Isso é um caso de ênfase; o tamanho é a evidência formal que sustenta a resposta.","errorReasons":["Conteúdo: nomear apenas “tamanho” sem reconhecer a relação de ênfase."]},
{...base,"id":"ART-FUN-001-EX-APR-05","statement":"O que distingue uma obra figurativa de uma obra naturalista?","answer":"Figurativa permite reconhecer figuras ou objetos; naturalista busca aproximar aspectos da aparência observável. Uma obra pode ser figurativa sem ser naturalista.","resolution":"Figuração diz respeito ao reconhecimento de referentes. Naturalismo é uma estratégia específica de representação. Um desenho simplificado de pessoa é figurativo mesmo sem buscar aparência realista.","errorReasons":["Conteúdo: tratar figurativo e naturalista como equivalentes."]},
{...base,"id":"ART-FUN-001-EX-APR-06","statement":"O que é estilização?","answer":"É selecionar, simplificar, exagerar ou reorganizar características de algo representado segundo uma proposta ou convenção.","resolution":"Estilizar não significa desenhar mal. É uma escolha de construção que pode sintetizar formas, aumentar expressividade ou seguir convenções visuais específicas.","errorReasons":["Conteúdo: confundir estilização com erro técnico."]},
{...base,"id":"ART-FUN-001-EX-APR-07","statement":"Qual deve vir primeiro numa leitura cuidadosa: descrição ou interpretação? Por quê?","answer":"A descrição deve vir antes, porque cria uma base observável para sustentar interpretações posteriores.","resolution":"Começar descrevendo reduz conclusões precipitadas. A interpretação pode vir depois, relacionando evidências formais, materiais e contextuais.","errorReasons":["Estratégia: saltar diretamente para uma mensagem ou emoção sem evidência."]},
{...base,"id":"ART-FUN-001-EX-APR-08","statement":"Uma interpretação artística precisa ser única para ser válida?","answer":"Não. Leituras diferentes podem ser defensáveis se forem coerentes com evidências da obra e contexto confiável.","resolution":"A aula rejeita tanto a resposta única automática quanto a ideia de que qualquer leitura vale. Interpretação funciona como argumento revisável.","errorReasons":["Argumentação: confundir pluralidade de leitura com ausência de critérios."]}
];
