const source={title:'ART-FUN-001 — Linguagens artísticas e leitura de obra — V2',url:'https://docs.google.com/document/d/15f2QMLEmsUWRk2VYjt9XqVRcVudxudnuh_pkFpiU8iM/edit',version:'V2'};
const base={"origin":"autoral","subject":"ART","topics":["ART-FUN-001"],"difficulty":"vestibular","layer":"VES","source":source,"reviewStatus":"revisado"};
export default [
{...base,"id":"ART-FUN-001-EX-VES-01","statement":"Um cartaz usa letras pequenas e regulares em quase toda a superfície, mas apresenta uma única palavra em letras muito grandes e inclinadas. Analise como a composição constrói hierarquia visual.","answer":"A repetição de letras pequenas cria um padrão; a mudança de escala e direção produz contraste e ênfase, tornando a palavra grande um ponto focal provável.","resolution":"Questões de transferência pedem relacionar descrição a conceitos. Aqui, escala, direção, contraste e repetição explicam a hierarquia sem exigir adivinhar o conteúdo temático.","errorReasons":["Estratégia: interpretar a mensagem sem analisar organização visual."]},
{...base,"id":"ART-FUN-001-EX-VES-02","statement":"Uma obra mostra um rosto reconhecível construído por poucos polígonos. Um estudante afirma: “não é figurativa porque não parece fotografia”. Avalie a afirmação.","answer":"A afirmação é incorreta. A obra continua figurativa porque o rosto é reconhecível; ela é estilizada e não precisa ser naturalista.","resolution":"O erro confunde figuração com naturalismo. Reconhecimento do referente basta para a categoria figurativa introdutória; fidelidade fotográfica é outra questão.","errorReasons":["Conteúdo: confundir reconhecimento com realismo."]},
{...base,"id":"ART-FUN-001-EX-VES-03","statement":"Uma performance acontece apenas quando o público entra em uma sala e seus movimentos ativam sons. Explique por que produto, processo e recepção ficam especialmente ligados nesse caso.","answer":"A obra depende da ação do público para acontecer; movimento, tecnologia, espaço e resposta sonora integram o processo e a experiência em tempo real.","resolution":"Não existe apenas um objeto independente do público. O acontecimento é produzido pela relação entre sistema, espaço e participação, tornando recepção parte constitutiva da obra.","errorReasons":["Transferência: insistir em procurar somente um objeto final."]},
{...base,"id":"ART-FUN-001-EX-VES-04","statement":"Uma obra foi criada como mural político em espaço público e décadas depois é transferida para um museu. Que perguntas de contexto e mediação são importantes para comparar as duas situações?","answer":"Perguntar quem era o público original, qual função tinha o espaço público, por que foi transferida, como o museu a apresenta e que informações ou restrições modificam a experiência.","resolution":"A mudança de lugar altera circulação, escala percebida, relação corporal, enquadramento institucional e mediação. A análise deve comparar condições sem presumir que o sentido ficou idêntico.","errorReasons":["Contexto: ignorar efeitos da mudança de circulação."]},
{...base,"id":"ART-FUN-001-EX-VES-05","statement":"Dois observadores oferecem interpretações diferentes da mesma obra. Um cita composição, material e contexto histórico; o outro diz apenas “para mim significa liberdade”. Qual interpretação está mais bem argumentada e por quê?","answer":"A primeira está mais bem argumentada porque apresenta evidências verificáveis e contexto; a segunda é apenas uma associação pessoal sem justificativa suficiente.","resolution":"Pluralidade interpretativa não elimina critérios. Uma leitura é mais forte quando explicita evidências, raciocínio e fontes, permitindo avaliação e revisão.","errorReasons":["Argumentação: confundir experiência pessoal com demonstração."]},
{...base,"id":"ART-FUN-001-EX-VES-06","statement":"Uma questão apresenta um objeto indígena em uma exposição e pergunta por seu sentido. Por que é metodologicamente inadequado tratá-lo apenas como forma decorativa sem investigar sua comunidade e função?","answer":"Porque formas e objetos podem integrar práticas, conhecimentos, identidades e usos específicos; separar aparência de contexto pode apagar significados culturais relevantes.","resolution":"A análise estética pode observar forma e material, mas precisa evitar reduzir manifestações culturais a decoração universal. Contexto e mediação são fundamentais para compreender função e sentido.","errorReasons":["Contexto cultural: universalizar categorias externas e apagar função social."]}
];
