const source={title:'SOC-FUN-001 — Sociedade, cultura e socialização — V2',url:'https://docs.google.com/document/d/1MKY44BDA3UXkz_Kc7CvH0akeJiEXAFmLnNfWFntTjtE/edit',version:'V2'};
const base={origin:'autoral',subject:'SOC',topics:['SOC-FUN-001'],difficulty:'consolidação',layer:'CON',source,reviewStatus:'revisado'};
export default [
{...base,id:'SOC-FUN-001-EX-CON-01',statement:'Uma empresa adota trabalho remoto e cria novas regras para reuniões, horários e comunicação. Mostre como isso evidencia mudança cultural e institucional.',answer:'Mudanças tecnológicas e organizacionais criam novas normas, expectativas e práticas; a instituição trabalho reorganiza sua cultura e seus mecanismos de coordenação.',resolution:'O trabalho remoto não é apenas troca de lugar físico. Ele exige aprender novas convenções, redefinir horários, canais, formas de supervisão e expectativas. Isso mostra cultura em mudança dentro de uma instituição social.',errorReasons:['Interpretação: enxergar apenas a tecnologia e ignorar normas, expectativas e relações.']},
{...base,id:'SOC-FUN-001-EX-CON-02',statement:'Explique por que dizer “todos os jovens pensam igual” é sociologicamente frágil.',answer:'Grupos geracionais são internamente diversos e variam por classe, região, gênero, religião, redes, experiências e outros fatores; a frase transforma diversidade em estereótipo.',resolution:'Uma categoria ampla pode apresentar tendências, mas não autoriza atribuir a mesma característica a todos os indivíduos. A Sociologia exige observar diversidade interna e contexto.',errorReasons:['Generalização: atribuir a todo um grupo uma característica observada em poucos casos.']},
{...base,id:'SOC-FUN-001-EX-CON-03',statement:'Dê um exemplo em que valor, norma e sanção apareçam juntos.',answer:'Exemplo: valor de respeito à ordem; norma de esperar na fila; sanção informal de reprovação a quem fura a fila.',resolution:'O valor fornece um ideal, a norma orienta a conduta concreta e a sanção responde ao cumprimento ou à violação da expectativa.',errorReasons:['Conteúdo: não distinguir valor, norma e sanção.']},
{...base,id:'SOC-FUN-001-EX-CON-04',statement:'Uma pessoa muda de país e precisa aprender novas convenções de cumprimento e horários. Que conceito explica esse processo?',answer:'Socialização secundária.',resolution:'A pessoa já possui aprendizagens sociais anteriores, mas entra em um novo contexto e precisa aprender regras e expectativas específicas. Isso caracteriza socialização secundária.',errorReasons:['Memória: associar socialização apenas à infância.']},
{...base,id:'SOC-FUN-001-EX-CON-05',statement:'Explique a diferença entre estrutura social e agência.',answer:'Estrutura refere-se a padrões, instituições e condições relativamente duradouras; agência é a capacidade de pessoas e grupos agirem dentro dessas condições e eventualmente transformá-las.',resolution:'A estrutura condiciona possibilidades, mas não determina mecanicamente cada ação. Agência também não significa liberdade ilimitada: agir ocorre dentro de condições sociais concretas.',errorReasons:['Estratégia: cair em determinismo social ou individualismo absoluto.']},
{...base,id:'SOC-FUN-001-EX-CON-06',statement:'Por que relativizar culturalmente não significa aceitar qualquer prática?',answer:'Relativizar é compreender contexto e significado; avaliação moral ou jurídica exige argumentos adicionais e pode levar à crítica.',resolution:'Compreensão e aprovação são operações diferentes. Contextualizar reduz julgamentos precipitados, mas não impede argumentação ética, jurídica ou política sobre a prática.',errorReasons:['Conteúdo: confundir contextualização com aprovação automática.']},
{...base,id:'SOC-FUN-001-EX-CON-07',statement:'Transforme a afirmação “sempre foi normal trabalhar oito horas por dia” em duas perguntas de desnaturalização.',answer:'Exemplos: “Quando essa jornada se tornou comum?” e “Que conflitos, leis e mudanças econômicas participaram de sua formação?”.',resolution:'As perguntas retiram a jornada do campo do “natural” e a colocam em investigação histórica e social. Outras perguntas comparativas e históricas equivalentes são válidas.',errorReasons:['Naturalização: aceitar a forma atual de organização como eterna ou inevitável.']},
{...base,id:'SOC-FUN-001-EX-CON-08',statement:'Um aluno respeita uma regra escolar mesmo quando nenhum professor está olhando. Que conceitos podem ajudar a explicar isso?',answer:'Socialização, internalização de normas, valores e sanções antecipadas.',resolution:'A regra pode ter sido aprendida como expectativa legítima, incorporada às rotinas e associada a valores e consequências. Controle social não depende apenas de vigilância direta.',errorReasons:['Interpretação: supor que normas só influenciam quando há fiscalização imediata.']}
];
