const source={title:'SOC-FUN-001 — Sociedade, cultura e socialização — V2',url:'https://docs.google.com/document/d/1MKY44BDA3UXkz_Kc7CvH0akeJiEXAFmLnNfWFntTjtE/edit',version:'V2'};
const base={origin:'autoral',subject:'SOC',topics:['SOC-FUN-001'],difficulty:'aprendizagem',layer:'APR',source,reviewStatus:'revisado'};
export default [
{...base,id:'SOC-FUN-001-EX-APR-01',statement:'Explique por que sociedade não pode ser definida apenas como muitas pessoas reunidas.',answer:'Sociedade envolve relações relativamente duradouras, instituições, normas, posições, valores e práticas; proximidade física por si só não basta.',resolution:'Uma multidão pode reunir muitas pessoas sem formar, por si só, a rede relativamente duradoura de relações, instituições, normas e práticas que o conceito sociológico de sociedade procura analisar.',errorReasons:['Conteúdo: reduzir sociedade à proximidade física ou à quantidade de indivíduos.']},
{...base,id:'SOC-FUN-001-EX-APR-02',statement:'Dê três exemplos de elementos culturais que não sejam obras de arte.',answer:'Exemplos possíveis: língua, regras de cumprimento e hábitos alimentares.',resolution:'Língua, regras de cumprimento e hábitos alimentares são aprendidos socialmente e possuem significados compartilhados. Também valem valores, costumes, conhecimentos, símbolos e técnicas.',errorReasons:['Conteúdo: usar cultura apenas como sinônimo de arte ou erudição.']},
{...base,id:'SOC-FUN-001-EX-APR-03',statement:'Qual é a diferença básica entre valor e norma?',answer:'Valor é uma ideia sobre o que é desejável ou importante; norma é uma expectativa ou regra mais concreta sobre comportamento.',resolution:'Valores funcionam como princípios ou ideais. Normas orientam condutas em situações concretas. Um valor pode sustentar várias normas.',errorReasons:['Conteúdo: confundir princípio valorativo com regra de comportamento.']},
{...base,id:'SOC-FUN-001-EX-APR-04',statement:'O que é socialização?',answer:'É o processo pelo qual pessoas aprendem linguagens, normas, valores, práticas, conhecimentos e papéis necessários à participação social.',resolution:'Socialização é aprendizagem social contínua. Ela começa cedo, mas também ocorre quando entramos em novos grupos, instituições e papéis.',errorReasons:['Memória: restringir socialização apenas à infância.']},
{...base,id:'SOC-FUN-001-EX-APR-05',statement:'Classifique: aprender a língua materna nos primeiros anos e aprender regras de uma profissão na vida adulta.',answer:'O primeiro caso é exemplo típico de socialização primária; o segundo, de socialização secundária.',resolution:'A primeira envolve aprendizagens iniciais e profundas em relações próximas. A segunda ocorre ao ingressar em um contexto específico que exige novos conhecimentos e papéis.',errorReasons:['Memória: trocar socialização primária e secundária.']},
{...base,id:'SOC-FUN-001-EX-APR-06',statement:'Uma multa de trânsito é que tipo de sanção?',answer:'É uma sanção negativa e formal.',resolution:'É negativa porque responde a uma conduta considerada inadequada e formal porque está prevista em regras institucionalizadas.',errorReasons:['Conteúdo: confundir sanção formal com reação informal.']},
{...base,id:'SOC-FUN-001-EX-APR-07',statement:'Por que uma escola é instituição social e não apenas um prédio?',answer:'Porque envolve regras, papéis, práticas, currículos, expectativas e relações organizadas que ultrapassam a estrutura física.',resolution:'A instituição escola continua existindo como conjunto organizado de relações e normas mesmo quando pensamos em unidades, prédios ou pessoas específicas diferentes.',errorReasons:['Conteúdo: confundir instituição social com edifício ou organização isolada.']},
{...base,id:'SOC-FUN-001-EX-APR-08',statement:'Explique em uma frase o que significa desnaturalizar uma prática social.',answer:'Significa investigar como uma prática foi histórica e socialmente construída em vez de tratá-la como inevitável por natureza.',resolution:'Desnaturalizar é transformar o “sempre foi assim” em problema de investigação: quando surgiu, como varia, como é aprendido e que processos o sustentam.',errorReasons:['Naturalização: tratar uma prática social como inevitável sem comparação histórica ou cultural.']}
];
