const source={title:'SOC-FUN-001 — Sociedade, cultura e socialização — V2',url:'https://docs.google.com/document/d/1MKY44BDA3UXkz_Kc7CvH0akeJiEXAFmLnNfWFntTjtE/edit',version:'V2'};
const base={origin:'autoral',subject:'SOC',topics:['SOC-FUN-001'],difficulty:'vestibular',layer:'VES',source,reviewStatus:'revisado'};
export default [
{...base,id:'SOC-FUN-001-EX-VES-01',statement:'Em uma cidade, restaurantes passam a oferecer cardápios digitais. Alguns clientes adotam rapidamente a prática; outros preferem cardápios impressos. Analise a situação usando os conceitos de cultura e mudança social.',answer:'A tecnologia introduz nova possibilidade material, mas sua incorporação depende de aprendizagem, hábitos, acesso e preferências; cultura muda de modo desigual.',resolution:'O cardápio digital é um elemento material associado a novas práticas e significados. Sua existência não produz adoção automática. Grupos podem aprender, resistir, adaptar e combinar práticas antigas e novas.',errorReasons:['Interpretação: tratar mudança tecnológica como mudança cultural automática e uniforme.']},
{...base,id:'SOC-FUN-001-EX-VES-02',statement:'Uma campanha afirma: “Se cada pessoa se esforçar, qualquer desigualdade desaparece”. Mostre por que a frase é sociologicamente incompleta.',answer:'A frase considera apenas agência individual e ignora estruturas como distribuição de recursos, instituições, oportunidades, discriminação e condições históricas.',resolution:'Esforço individual pode produzir efeitos, mas ocorre dentro de condições desiguais. A análise sociológica relaciona agência a estruturas e não reduz resultados sociais a uma única causa individual.',errorReasons:['Estratégia: explicar fenômenos coletivos apenas por escolhas individuais.']},
{...base,id:'SOC-FUN-001-EX-VES-03',statement:'Em uma escola, usar boné em sala gera reprovação; em outro espaço social, o boné é sinal de pertencimento. O que o contraste demonstra?',answer:'Demonstra que significados, normas e símbolos dependem do contexto social; o mesmo objeto pode receber interpretações diferentes.',resolution:'O objeto físico é o mesmo, mas as regras e os significados compartilhados variam. Isso evidencia o caráter contextual dos símbolos e das normas.',errorReasons:['Conteúdo: tratar o significado de um símbolo como fixo e universal.']},
{...base,id:'SOC-FUN-001-EX-VES-04',statement:'Um observador chama um costume estrangeiro de “atrasado” apenas porque é diferente do seu. Identifique o problema analítico.',answer:'Etnocentrismo.',resolution:'O observador usa o próprio padrão cultural como medida universal e julga sem investigar contexto e significado. A análise sociológica pede primeiro compreensão contextual.',errorReasons:['Etnocentrismo: tomar o próprio costume como medida universal de superioridade.']},
{...base,id:'SOC-FUN-001-EX-VES-05',statement:'Explique por que mudanças na linguagem usada por um grupo podem ser analisadas como fenômeno social, mesmo quando cada falante escolhe palavras individualmente.',answer:'Escolhas individuais ocorrem dentro de convenções compartilhadas; quando muitas interações alteram usos e significados, a língua muda coletivamente, mostrando relação entre agência e estrutura.',resolution:'Falantes possuem agência, mas precisam de convenções para serem compreendidos. Repetidas escolhas e interações podem estabilizar novas convenções, alterando a estrutura linguística compartilhada.',errorReasons:['Estratégia: separar completamente escolhas individuais de padrões coletivos.']},
{...base,id:'SOC-FUN-001-EX-VES-06',statement:'Uma criança aprende que deve agradecer quando recebe ajuda. Identifique pelo menos quatro conceitos sociológicos presentes.',answer:'Socialização; norma de agradecer; valor de reconhecimento ou cortesia; agentes de socialização; possível sanção positiva quando a conduta é elogiada.',resolution:'A situação reúne aprendizagem social, uma expectativa de comportamento, valores que a justificam, pessoas ou instituições que a ensinam e respostas sociais que reforçam a conduta.',errorReasons:['Conteúdo: identificar apenas a regra e ignorar o processo de aprendizagem e os valores associados.']}
];
