import {useEffect,useRef} from 'react';
import diagnostic from './content/diagnostic.json';
import type {StudyState} from './model';
export default function Diagnostic({state,update,current,storageError}:{state:StudyState;update:(f:(s:StudyState)=>StudyState)=>void;current?:string;storageError:boolean}){
 const index=Math.max(0,diagnostic.questions.findIndex(q=>q.id===current));const q=diagnostic.questions[index];const field=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{field.current?.focus()},[q.id]);
 const save=(answer:string)=>update(s=>({...s,answers:{...s.answers,[q.id]:answer},cursor:q.id}));
 const move=(id:string)=>{update(s=>({...s,cursor:id}));location.hash='diagnostico/'+id};
 const notation:Record<string,string>={'M1':'Quarenta e sete mais trinta e oito.','M2':'Cento e vinte e cinco menos setenta e nove.','M3':'Oito vezes sete.','M4':'Cento e quarenta e quatro dividido por doze.','M5':'Seis mais quatro vezes três.','M6':'Três inteiros e cinco décimos mais dois inteiros e setenta e cinco centésimos.','M7':'Alternativas: três quintos; três oitavos; cinco oitavos; oito terços.','M8':'Um meio mais um quarto.','M14':'Menos cinco mais doze.','M15':'X mais sete igual a dezenove.','M16':'Dois vezes x igual a dezoito.','M17':'Dois elevado ao cubo.','M24':'Um quarto desse valor.'};
 return <><p className="eyebrow">DIA-001 · AUTORAL · SEM NOTA DE APROVAÇÃO</p><h1>Conheça sua base.</h1><p className="intro">Um diagnóstico para orientar seu percurso, não para medir sua inteligência.</p><details><summary>Objetivo e orientações completas</summary><div className="source-text">{diagnostic.introduction}</div></details><div className="diagnostic-layout"><aside className="question-nav" aria-label="Índice do diagnóstico"><h2>Suas questões</h2><p>{Object.values(state.answers).filter(Boolean).length} respostas registradas</p><nav aria-label="Questões do diagnóstico">{diagnostic.questions.map((x,i)=><a href={`#diagnostico/${x.id}`} key={x.id} aria-current={i===index?'step':undefined} aria-label={`${x.originalId}${state.answers[x.id]?.trim()?', resposta registrada':''}`} onClick={()=>update(s=>({...s,cursor:x.id}))}>{x.originalId}{state.answers[x.id]?.trim()?' ✓':''}</a>)}</nav><a href="#progresso">Exportar respostas →</a></aside><article className="question"><p className="eyebrow">QUESTÃO {index+1} DE 37 · {q.subject==='MAT'?'MATEMÁTICA':'LÍNGUA PORTUGUESA'}</p>{index<4&&<section><h2>Texto de leitura</h2><blockquote>{diagnostic.reading}</blockquote></section>}<h2>{q.originalId} · {q.originalId==='P13'?'Produção escrita':'Registre seu raciocínio'}</h2><div className="source-text">{q.statement}</div>{notation[q.originalId]&&<p className="spoken">Leitura da notação: {notation[q.originalId]}</p>}<label className="answer-label" htmlFor="answer">Sua resposta e os passos que utilizou</label><textarea id="answer" ref={field} rows={q.originalId==='P13'?12:5} value={state.answers[q.id]||''} onChange={e=>save(e.target.value)} placeholder="Escreva sua resposta. Você também pode registrar: não sei."/><p className="small">{storageError?'Use Exportar respostas para guardar uma cópia.':'Respostas salvas automaticamente neste navegador.'}</p><div className="question-actions"><button disabled={index===0} onClick={()=>move(diagnostic.questions[index-1].id)}>← Anterior</button>{index<36?<button className="primary" onClick={()=>move(diagnostic.questions[index+1].id)}>Próxima →</button>:<a className="button primary" href="#progresso">Ver respostas registradas →</a>}</div><div className="note"><h3>Correção pedagógica pendente</h3><p>O documento original não contém gabarito nem resolução. Suas respostas serão usadas na correção posterior. Nenhum tópico será consolidado automaticamente.</p><a href="#erros">Anotar uma dificuldade no Caderno de Erros →</a></div></article></div><details><summary>Autoavaliação e critérios de análise</summary><div className="source-text">{diagnostic.closing}</div><label>Suas observações<textarea rows={4} value={state.answers['DIA-001-AUTO']||''} onChange={e=>update(s=>({...s,answers:{...s.answers,'DIA-001-AUTO':e.target.value}}))}/></label></details><p><a href={diagnostic.source.url} target="_blank" rel="noreferrer">Consultar documento original no Google Drive</a></p></>;
}

