import {useEffect,useState} from 'react';
import {loadLesson,topics,questions} from './catalog';
import type {Lesson,Section,StudyState,Status} from './model';
import {canConsolidate,emptyProgress} from './study';
function ContentSection({section:s}:{section:Section}){return <section id={s.id}><h2>{s.title}</h2>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{s.formula&&<div className="note"><p>{s.formula.notation}</p><p>{s.formula.spoken}</p><p>{s.formula.variables}</p><p>{s.formula.units}</p><p>{s.formula.example}</p></div>}{s.visuals?.map(v=><figure key={v.url}><img src={v.url} alt={v.alt} loading="lazy"/><figcaption>{v.caption}</figcaption><p>{v.observe}</p><p>{v.conclusion}</p>{v.source&&<a href={v.source.url}>{v.source.title}</a>}</figure>)}</section>}
export default function LessonPage({id,state,update}:{id:string;state:StudyState;update:(f:(s:StudyState)=>StudyState)=>void}){
 const [lesson,setLesson]=useState<Lesson>(),[error,setError]=useState('');
 const topic=topics.find(t=>t.id===id&&t.editorialStatus==='publicado');
 useEffect(()=>{setLesson(undefined);setError('');if(!topic){setError('Esta aula ainda não está publicada.');return;}let active=true;loadLesson(id).then(l=>{if(active)setLesson(l)}).catch(()=>setError('Não foi possível abrir a aula.'));return()=>{active=false}},[id,topic]);
 if(error)return <><h1>Aula indisponível</h1><p>{error}</p><a href="#aulas">Consultar a biblioteca</a></>;
 if(!lesson||!topic)return <p>Carregando aula…</p>;
 const p=state.topics[id]||emptyProgress();
 return <><p className="eyebrow">{id}</p><h1>{topic.title}</h1><p>{lesson.objective}</p><nav aria-label="Índice da aula">{lesson.sections.map(s=><a key={s.id} href={`#${s.id}`} onClick={e=>{e.preventDefault();document.getElementById(s.id)?.scrollIntoView()}}>{s.title} · </a>)}</nav><article>{lesson.sections.map(s=><ContentSection key={s.id} section={s}/>)}</article><section><h2>Prática e correção comentada</h2>{questions.filter(q=>q.topics.includes(id)&&q.reviewStatus==='revisado').map(q=><div className="note" key={q.id}><h3>{q.id} · {q.origin}</h3><p>{q.statement}</p><details><summary>Consultar raciocínio</summary><p>{q.answer}</p><p>{q.resolution}</p></details></div>)}</section><h2>Resumo para ouvir</h2><p>{lesson.audioVersion}</p>{lesson.video&&<section><h2>Vídeo complementar</h2><a href={lesson.video.url}>{lesson.video.title} — {lesson.video.channel}</a><p>{lesson.video.duration} · {lesson.video.language}</p><p>{lesson.video.reason} {lesson.video.when}</p></section>}<label>Estado de aprendizagem<select value={p.status} onChange={e=>{const status=e.target.value as Status;if(status==='consolidado'&&!canConsolidate(p))return;update(s=>({...s,topics:{...s.topics,[id]:{...p,status,lastStudy:new Date().toISOString()}}}))}}>{['não iniciado','aprendendo','revisar','consolidado'].map(s=><option key={s} disabled={s==='consolidado'&&!canConsolidate(p)}>{s}</option>)}</select></label><p>A consolidação exige evidências em exercícios, aplicação, transferência, explicação e revisão.</p>{lesson.next&&topics.some(t=>t.id===lesson.next&&t.editorialStatus==='publicado')&&<a href={`#aula/${lesson.next}`}>Próximo tópico →</a>}</>;
}
