export type Status = 'não iniciado' | 'aprendendo' | 'revisar' | 'consolidado';
export type ErrorKind = 'conteúdo' | 'interpretação' | 'cálculo' | 'distração' | 'memória' | 'estratégia' | 'tempo';
export interface Source {title:string;url:string;checkedAt?:string;version?:string}
export interface Visual {url:string;caption:string;alt:string;observe:string;conclusion:string;source?:Source;axes?:{horizontal:string;vertical:string;units:string;scale:string}}
export interface Video {title:string;channel:string;url:string;duration:string;language:string;reason:string;when:string;reinforces:string[];checkedAt:string;verification?:string;type?:'video'|'leitura'}
export interface Topic {id:string;title:string;subject:string;unit:string;level:1|2|3|4|5|6;order:number;description:string;prerequisites:string[];objectives:string[];skills:string[];related:string[];applications:string[];exams:string[];depth:string;visuals:Visual[];exercises:string[];review:{summary:string;intervals:number[]};next?:string;editorialStatus:'publicado'|'conteúdo a recuperar'|'planejado';source:Source}
export type TopicSummary = Pick<Topic,'id'|'title'|'subject'|'unit'|'level'|'order'|'prerequisites'|'exercises'|'next'|'editorialStatus'> & {visualCount:number};
export interface Section {id:string;title:string;paragraphs:string[];markdown?:string;sourceStart?:number;sourceEnd?:number;formula?:{notation:string;spoken:string;variables:string;units:string;example:string};visuals?:Visual[]}
export interface Lesson {id:string;version:string;objective:string;prerequisites:string[];why:string;intuitive:Section[];deep:Section[];vocabulary:{term:string;meaning:string}[];examples:Section[];visuals:Visual[];applications:string[];connections:string[];commonErrors:string[];learning:string[];consolidation:string[];entrance:string[];retest?:string[];solutions:Section[];summary:string;audioVersion:string;video?:Video;videos?:Video[];next?:string;previous?:string;sections:Section[];sources:Source[];publication?:PublicationInfo}
export interface Question {id:string;origin:'oficial'|'autoral'|'adaptada';exam?:string;year?:number;subject:string;topics:string[];difficulty:'aprendizagem'|'consolidação'|'vestibular'|'diagnóstico'|'reteste';layer?:string;title?:string;statement:string;alternatives?:string[];answer?:string;resolution?:string;errorReasons?:string[];source:Source;reviewStatus:'pendente'|'revisado';reviewNote?:string}
export type QuestionSummary = Pick<Question,'id'|'origin'|'subject'|'topics'|'difficulty'|'layer'|'reviewStatus'|'source'>;
export interface LessonEdition {label:string;url:string}
export interface PublicationInfo {kind:string;notes:string[];original:string;editions:LessonEdition[];attachments:LessonEdition[];questionCount:number;visualCount:number;sourceSha256:string}
export interface TopicProgress {status:Status;lastStudy?:string;attempts:number;correct:number;incorrect:number;reviews:number;confidence:number;nextStep:string;reviewDate?:string;evidence:{explained:boolean;direct:boolean;application:boolean;transfer:boolean;recall:boolean}}
export interface Revision<T> {at:string;value:T}
export interface StudyHistory {answers:Record<string,Revision<string>[]>;topics:Record<string,Revision<TopicProgress>[]>;errors:Record<string,Revision<StudyState['errors'][number]>[]>}
export interface StudyState {history?:StudyHistory;version:1;answers:Record<string,string>;cursor?:string;topics:Record<string,TopicProgress>;errors:{id:string;question:string;kind:ErrorKind;note:string;date:string;resolved:boolean}[];updatedAt:string}
