export type Status = 'não iniciado' | 'aprendendo' | 'revisar' | 'consolidado';
export type ErrorKind = 'conteúdo' | 'interpretação' | 'cálculo' | 'distração' | 'memória' | 'estratégia' | 'tempo';
export interface Source {title:string;url:string;checkedAt?:string;version?:string}
export interface Visual {url:string;caption:string;alt:string;observe:string;conclusion:string;source?:Source;axes?:{horizontal:string;vertical:string;units:string;scale:string}}
export interface Video {title:string;channel:string;url:string;duration:string;language:string;reason:string;when:string;reinforces:string[];checkedAt:string}
export interface Topic {id:string;title:string;subject:string;unit:string;level:1|2|3|4|5|6;order:number;description:string;prerequisites:string[];objectives:string[];skills:string[];related:string[];applications:string[];exams:string[];depth:string;visuals:Visual[];exercises:string[];review:{summary:string;intervals:number[]};next?:string;editorialStatus:'publicado'|'conteúdo a recuperar'|'planejado';source:Source}
export interface Section {id:string;title:string;paragraphs:string[];formula?:{notation:string;spoken:string;variables:string;units:string;example:string};visuals?:Visual[]}
export interface Lesson {id:string;version:string;objective:string;prerequisites:string[];why:string;intuitive:Section[];deep:Section[];vocabulary:{term:string;meaning:string}[];examples:Section[];visuals:Visual[];applications:string[];connections:string[];commonErrors:string[];learning:string[];consolidation:string[];entrance:string[];solutions:Section[];summary:string;audioVersion:string;video?:Video;next?:string;sections:Section[];sources:Source[]}
export interface Question {id:string;origin:'oficial'|'autoral'|'adaptada';exam?:string;year?:number;subject:string;topics:string[];difficulty:'aprendizagem'|'consolidação'|'vestibular'|'diagnóstico';statement:string;alternatives?:string[];answer?:string;resolution?:string;errorReasons?:string[];source:Source;reviewStatus:'pendente'|'revisado'}
export interface TopicProgress {status:Status;lastStudy?:string;attempts:number;correct:number;incorrect:number;reviews:number;confidence:number;nextStep:string;reviewDate?:string;evidence:{explained:boolean;direct:boolean;application:boolean;transfer:boolean;recall:boolean}}
export interface StudyState {version:1;answers:Record<string,string>;cursor?:string;topics:Record<string,TopicProgress>;errors:{id:string;question:string;kind:ErrorKind;note:string;date:string;resolved:boolean}[];updatedAt:string}
